package com.haoding.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EntrustTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public EntrustTableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEntrustIdIsNull() {
            addCriterion("entrust_id is null");
            return (Criteria) this;
        }

        public Criteria andEntrustIdIsNotNull() {
            addCriterion("entrust_id is not null");
            return (Criteria) this;
        }

        public Criteria andEntrustIdEqualTo(String value) {
            addCriterion("entrust_id =", value, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdNotEqualTo(String value) {
            addCriterion("entrust_id <>", value, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdGreaterThan(String value) {
            addCriterion("entrust_id >", value, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdGreaterThanOrEqualTo(String value) {
            addCriterion("entrust_id >=", value, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdLessThan(String value) {
            addCriterion("entrust_id <", value, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdLessThanOrEqualTo(String value) {
            addCriterion("entrust_id <=", value, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdLike(String value) {
            addCriterion("entrust_id like", value, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdNotLike(String value) {
            addCriterion("entrust_id not like", value, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdIn(List<String> values) {
            addCriterion("entrust_id in", values, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdNotIn(List<String> values) {
            addCriterion("entrust_id not in", values, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdBetween(String value1, String value2) {
            addCriterion("entrust_id between", value1, value2, "entrustId");
            return (Criteria) this;
        }

        public Criteria andEntrustIdNotBetween(String value1, String value2) {
            addCriterion("entrust_id not between", value1, value2, "entrustId");
            return (Criteria) this;
        }

        public Criteria andStockIdIsNull() {
            addCriterion("stock_id is null");
            return (Criteria) this;
        }

        public Criteria andStockIdIsNotNull() {
            addCriterion("stock_id is not null");
            return (Criteria) this;
        }

        public Criteria andStockIdEqualTo(Integer value) {
            addCriterion("stock_id =", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotEqualTo(Integer value) {
            addCriterion("stock_id <>", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdGreaterThan(Integer value) {
            addCriterion("stock_id >", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock_id >=", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdLessThan(Integer value) {
            addCriterion("stock_id <", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdLessThanOrEqualTo(Integer value) {
            addCriterion("stock_id <=", value, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdIn(List<Integer> values) {
            addCriterion("stock_id in", values, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotIn(List<Integer> values) {
            addCriterion("stock_id not in", values, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdBetween(Integer value1, Integer value2) {
            addCriterion("stock_id between", value1, value2, "stockId");
            return (Criteria) this;
        }

        public Criteria andStockIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stock_id not between", value1, value2, "stockId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeIsNull() {
            addCriterion("resting_order_time is null");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeIsNotNull() {
            addCriterion("resting_order_time is not null");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeEqualTo(Date value) {
            addCriterion("resting_order_time =", value, "restingOrderTime");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeNotEqualTo(Date value) {
            addCriterion("resting_order_time <>", value, "restingOrderTime");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeGreaterThan(Date value) {
            addCriterion("resting_order_time >", value, "restingOrderTime");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("resting_order_time >=", value, "restingOrderTime");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeLessThan(Date value) {
            addCriterion("resting_order_time <", value, "restingOrderTime");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeLessThanOrEqualTo(Date value) {
            addCriterion("resting_order_time <=", value, "restingOrderTime");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeIn(List<Date> values) {
            addCriterion("resting_order_time in", values, "restingOrderTime");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeNotIn(List<Date> values) {
            addCriterion("resting_order_time not in", values, "restingOrderTime");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeBetween(Date value1, Date value2) {
            addCriterion("resting_order_time between", value1, value2, "restingOrderTime");
            return (Criteria) this;
        }

        public Criteria andRestingOrderTimeNotBetween(Date value1, Date value2) {
            addCriterion("resting_order_time not between", value1, value2, "restingOrderTime");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeIsNull() {
            addCriterion("cancellation_time is null");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeIsNotNull() {
            addCriterion("cancellation_time is not null");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeEqualTo(Date value) {
            addCriterion("cancellation_time =", value, "cancellationTime");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeNotEqualTo(Date value) {
            addCriterion("cancellation_time <>", value, "cancellationTime");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeGreaterThan(Date value) {
            addCriterion("cancellation_time >", value, "cancellationTime");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cancellation_time >=", value, "cancellationTime");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeLessThan(Date value) {
            addCriterion("cancellation_time <", value, "cancellationTime");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeLessThanOrEqualTo(Date value) {
            addCriterion("cancellation_time <=", value, "cancellationTime");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeIn(List<Date> values) {
            addCriterion("cancellation_time in", values, "cancellationTime");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeNotIn(List<Date> values) {
            addCriterion("cancellation_time not in", values, "cancellationTime");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeBetween(Date value1, Date value2) {
            addCriterion("cancellation_time between", value1, value2, "cancellationTime");
            return (Criteria) this;
        }

        public Criteria andCancellationTimeNotBetween(Date value1, Date value2) {
            addCriterion("cancellation_time not between", value1, value2, "cancellationTime");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeIsNull() {
            addCriterion("entrust_time is null");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeIsNotNull() {
            addCriterion("entrust_time is not null");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeEqualTo(Date value) {
            addCriterion("entrust_time =", value, "entrustTime");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeNotEqualTo(Date value) {
            addCriterion("entrust_time <>", value, "entrustTime");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeGreaterThan(Date value) {
            addCriterion("entrust_time >", value, "entrustTime");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("entrust_time >=", value, "entrustTime");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeLessThan(Date value) {
            addCriterion("entrust_time <", value, "entrustTime");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeLessThanOrEqualTo(Date value) {
            addCriterion("entrust_time <=", value, "entrustTime");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeIn(List<Date> values) {
            addCriterion("entrust_time in", values, "entrustTime");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeNotIn(List<Date> values) {
            addCriterion("entrust_time not in", values, "entrustTime");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeBetween(Date value1, Date value2) {
            addCriterion("entrust_time between", value1, value2, "entrustTime");
            return (Criteria) this;
        }

        public Criteria andEntrustTimeNotBetween(Date value1, Date value2) {
            addCriterion("entrust_time not between", value1, value2, "entrustTime");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrust_table
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}