package com.haoding.po;

import java.util.Date;

public class HistoryTradeTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_trade_table.trade_id
     *
     * @mbggenerated
     */
    private String tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_trade_table.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_trade_table.stock_id
     *
     * @mbggenerated
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_trade_table.trade_price
     *
     * @mbggenerated
     */
    private Double tradePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_trade_table.trade_time
     *
     * @mbggenerated
     */
    private Date tradeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_trade_table.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_trade_table
     *
     * @mbggenerated
     */
    public HistoryTradeTable(String tradeId, Integer userId, Integer stockId, Double tradePrice, Date tradeTime, String type) {
        this.tradeId = tradeId;
        this.userId = userId;
        this.stockId = stockId;
        this.tradePrice = tradePrice;
        this.tradeTime = tradeTime;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_trade_table.trade_id
     *
     * @return the value of history_trade_table.trade_id
     *
     * @mbggenerated
     */
    public String getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_trade_table.user_id
     *
     * @return the value of history_trade_table.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_trade_table.stock_id
     *
     * @return the value of history_trade_table.stock_id
     *
     * @mbggenerated
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_trade_table.trade_price
     *
     * @return the value of history_trade_table.trade_price
     *
     * @mbggenerated
     */
    public Double getTradePrice() {
        return tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_trade_table.trade_time
     *
     * @return the value of history_trade_table.trade_time
     *
     * @mbggenerated
     */
    public Date getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_trade_table.type
     *
     * @return the value of history_trade_table.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }
}