package com.haoding.po;

import java.util.Date;

public class NewsTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_table.news_id
     *
     * @mbggenerated
     */
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_table.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_table.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_table.news
     *
     * @mbggenerated
     */
    private String news;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_table
     *
     * @mbggenerated
     */
    public NewsTable(Integer newsId, Date time, String type, String news) {
        this.newsId = newsId;
        this.time = time;
        this.type = type;
        this.news = news;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_table.news_id
     *
     * @return the value of news_table.news_id
     *
     * @mbggenerated
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_table.time
     *
     * @return the value of news_table.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_table.type
     *
     * @return the value of news_table.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_table.news
     *
     * @return the value of news_table.news
     *
     * @mbggenerated
     */
    public String getNews() {
        return news;
    }
}