package com.haoding.po;

public class StockBar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_bar.post_content_id
     *
     * @mbggenerated
     */
    private Integer postContentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_bar.stock_id
     *
     * @mbggenerated
     */
    private Integer stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_bar.post_time
     *
     * @mbggenerated
     */
    private String postTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_bar.post_content
     *
     * @mbggenerated
     */
    private String postContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar
     *
     * @mbggenerated
     */
    public StockBar(Integer postContentId, Integer stockId, String postTime, String postContent) {
        this.postContentId = postContentId;
        this.stockId = stockId;
        this.postTime = postTime;
        this.postContent = postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_bar.post_content_id
     *
     * @return the value of stock_bar.post_content_id
     *
     * @mbggenerated
     */
    public Integer getPostContentId() {
        return postContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_bar.stock_id
     *
     * @return the value of stock_bar.stock_id
     *
     * @mbggenerated
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_bar.post_time
     *
     * @return the value of stock_bar.post_time
     *
     * @mbggenerated
     */
    public String getPostTime() {
        return postTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_bar.post_content
     *
     * @return the value of stock_bar.post_content
     *
     * @mbggenerated
     */
    public String getPostContent() {
        return postContent;
    }
}