package com.haoding.po;

import java.util.ArrayList;
import java.util.List;

public class StockBarReplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public StockBarReplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStockBarReplyIdIsNull() {
            addCriterion("stock_bar_reply_id is null");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdIsNotNull() {
            addCriterion("stock_bar_reply_id is not null");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdEqualTo(Integer value) {
            addCriterion("stock_bar_reply_id =", value, "stockBarReplyId");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdNotEqualTo(Integer value) {
            addCriterion("stock_bar_reply_id <>", value, "stockBarReplyId");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdGreaterThan(Integer value) {
            addCriterion("stock_bar_reply_id >", value, "stockBarReplyId");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock_bar_reply_id >=", value, "stockBarReplyId");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdLessThan(Integer value) {
            addCriterion("stock_bar_reply_id <", value, "stockBarReplyId");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdLessThanOrEqualTo(Integer value) {
            addCriterion("stock_bar_reply_id <=", value, "stockBarReplyId");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdIn(List<Integer> values) {
            addCriterion("stock_bar_reply_id in", values, "stockBarReplyId");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdNotIn(List<Integer> values) {
            addCriterion("stock_bar_reply_id not in", values, "stockBarReplyId");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdBetween(Integer value1, Integer value2) {
            addCriterion("stock_bar_reply_id between", value1, value2, "stockBarReplyId");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stock_bar_reply_id not between", value1, value2, "stockBarReplyId");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeIsNull() {
            addCriterion("stock_bar_reply_time is null");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeIsNotNull() {
            addCriterion("stock_bar_reply_time is not null");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeEqualTo(String value) {
            addCriterion("stock_bar_reply_time =", value, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeNotEqualTo(String value) {
            addCriterion("stock_bar_reply_time <>", value, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeGreaterThan(String value) {
            addCriterion("stock_bar_reply_time >", value, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeGreaterThanOrEqualTo(String value) {
            addCriterion("stock_bar_reply_time >=", value, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeLessThan(String value) {
            addCriterion("stock_bar_reply_time <", value, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeLessThanOrEqualTo(String value) {
            addCriterion("stock_bar_reply_time <=", value, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeLike(String value) {
            addCriterion("stock_bar_reply_time like", value, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeNotLike(String value) {
            addCriterion("stock_bar_reply_time not like", value, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeIn(List<String> values) {
            addCriterion("stock_bar_reply_time in", values, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeNotIn(List<String> values) {
            addCriterion("stock_bar_reply_time not in", values, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeBetween(String value1, String value2) {
            addCriterion("stock_bar_reply_time between", value1, value2, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andStockBarReplyTimeNotBetween(String value1, String value2) {
            addCriterion("stock_bar_reply_time not between", value1, value2, "stockBarReplyTime");
            return (Criteria) this;
        }

        public Criteria andReplayedIdIsNull() {
            addCriterion("replayed_id is null");
            return (Criteria) this;
        }

        public Criteria andReplayedIdIsNotNull() {
            addCriterion("replayed_id is not null");
            return (Criteria) this;
        }

        public Criteria andReplayedIdEqualTo(Integer value) {
            addCriterion("replayed_id =", value, "replayedId");
            return (Criteria) this;
        }

        public Criteria andReplayedIdNotEqualTo(Integer value) {
            addCriterion("replayed_id <>", value, "replayedId");
            return (Criteria) this;
        }

        public Criteria andReplayedIdGreaterThan(Integer value) {
            addCriterion("replayed_id >", value, "replayedId");
            return (Criteria) this;
        }

        public Criteria andReplayedIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("replayed_id >=", value, "replayedId");
            return (Criteria) this;
        }

        public Criteria andReplayedIdLessThan(Integer value) {
            addCriterion("replayed_id <", value, "replayedId");
            return (Criteria) this;
        }

        public Criteria andReplayedIdLessThanOrEqualTo(Integer value) {
            addCriterion("replayed_id <=", value, "replayedId");
            return (Criteria) this;
        }

        public Criteria andReplayedIdIn(List<Integer> values) {
            addCriterion("replayed_id in", values, "replayedId");
            return (Criteria) this;
        }

        public Criteria andReplayedIdNotIn(List<Integer> values) {
            addCriterion("replayed_id not in", values, "replayedId");
            return (Criteria) this;
        }

        public Criteria andReplayedIdBetween(Integer value1, Integer value2) {
            addCriterion("replayed_id between", value1, value2, "replayedId");
            return (Criteria) this;
        }

        public Criteria andReplayedIdNotBetween(Integer value1, Integer value2) {
            addCriterion("replayed_id not between", value1, value2, "replayedId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_bar_reply
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}