package com.haoding.mapper;

import com.haoding.po.EntrustTable;
import com.haoding.po.EntrustTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface EntrustTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    int countByExample(EntrustTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    int deleteByExample(EntrustTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    @Insert({
        "insert into entrust_table (entrust_id, stock_id, ",
        "user_id, resting_order_time, ",
        "cancellation_time, entrust_time, ",
        "price)",
        "values (#{entrustId,jdbcType=CHAR}, #{stockId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{restingOrderTime,jdbcType=TIMESTAMP}, ",
        "#{cancellationTime,jdbcType=TIMESTAMP}, #{entrustTime,jdbcType=TIMESTAMP}, ",
        "#{price,jdbcType=DOUBLE})"
    })
    int insert(EntrustTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    int insertSelective(EntrustTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    List<EntrustTable> selectByExample(EntrustTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EntrustTable record, @Param("example") EntrustTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EntrustTable record, @Param("example") EntrustTableExample example);
}