package com.haoding.mapper;

import com.haoding.po.HistoryTradeTable;
import com.haoding.po.HistoryTradeTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface HistoryTradeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_trade_table
     *
     * @mbggenerated
     */
    int countByExample(HistoryTradeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_trade_table
     *
     * @mbggenerated
     */
    int deleteByExample(HistoryTradeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_trade_table
     *
     * @mbggenerated
     */
    @Insert({
        "insert into history_trade_table (trade_id, user_id, ",
        "stock_id, trade_price, ",
        "trade_time, type)",
        "values (#{tradeId,jdbcType=VARCHAR}, #{userId,jdbcType=INTEGER}, ",
        "#{stockId,jdbcType=INTEGER}, #{tradePrice,jdbcType=DOUBLE}, ",
        "#{tradeTime,jdbcType=TIMESTAMP}, #{type,jdbcType=VARCHAR})"
    })
    int insert(HistoryTradeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_trade_table
     *
     * @mbggenerated
     */
    int insertSelective(HistoryTradeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_trade_table
     *
     * @mbggenerated
     */
    List<HistoryTradeTable> selectByExample(HistoryTradeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_trade_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HistoryTradeTable record, @Param("example") HistoryTradeTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_trade_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HistoryTradeTable record, @Param("example") HistoryTradeTableExample example);
}