package com.haoding.mapper;

import com.haoding.po.NewsTable;
import com.haoding.po.NewsTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface NewsTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_table
     *
     * @mbggenerated
     */
    int countByExample(NewsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_table
     *
     * @mbggenerated
     */
    int deleteByExample(NewsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_table
     *
     * @mbggenerated
     */
    @Insert({
        "insert into news_table (news_id, time, ",
        "type, news)",
        "values (#{newsId,jdbcType=INTEGER}, #{time,jdbcType=TIMESTAMP}, ",
        "#{type,jdbcType=VARCHAR}, #{news,jdbcType=LONGVARCHAR})"
    })
    int insert(NewsTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_table
     *
     * @mbggenerated
     */
    int insertSelective(NewsTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_table
     *
     * @mbggenerated
     */
    List<NewsTable> selectByExampleWithBLOBs(NewsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_table
     *
     * @mbggenerated
     */
    List<NewsTable> selectByExample(NewsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_table
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NewsTable record, @Param("example") NewsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_table
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") NewsTable record, @Param("example") NewsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_table
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NewsTable record, @Param("example") NewsTableExample example);
}