package com.haoding.mapper;

import com.haoding.po.StockBarReply;
import com.haoding.po.StockBarReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface StockBarReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    int countByExample(StockBarReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    int deleteByExample(StockBarReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    @Insert({
        "insert into stock_bar_reply (stock_bar_reply_id, stock_bar_reply_time, ",
        "replayed_id, stock_bar_reply_content)",
        "values (#{stockBarReplyId,jdbcType=INTEGER}, #{stockBarReplyTime,jdbcType=VARCHAR}, ",
        "#{replayedId,jdbcType=INTEGER}, #{stockBarReplyContent,jdbcType=LONGVARCHAR})"
    })
    int insert(StockBarReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    int insertSelective(StockBarReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    List<StockBarReply> selectByExampleWithBLOBs(StockBarReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    List<StockBarReply> selectByExample(StockBarReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockBarReply record, @Param("example") StockBarReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") StockBarReply record, @Param("example") StockBarReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar_reply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockBarReply record, @Param("example") StockBarReplyExample example);
}