package com.haoding.mapper;

import com.haoding.po.StockBar;
import com.haoding.po.StockBarExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface StockBarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar
     *
     * @mbggenerated
     */
    int countByExample(StockBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar
     *
     * @mbggenerated
     */
    int deleteByExample(StockBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar
     *
     * @mbggenerated
     */
    @Insert({
        "insert into stock_bar (post_content_id, stock_id, ",
        "post_time, post_content)",
        "values (#{postContentId,jdbcType=INTEGER}, #{stockId,jdbcType=INTEGER}, ",
        "#{postTime,jdbcType=VARCHAR}, #{postContent,jdbcType=LONGVARCHAR})"
    })
    int insert(StockBar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar
     *
     * @mbggenerated
     */
    int insertSelective(StockBar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar
     *
     * @mbggenerated
     */
    List<StockBar> selectByExampleWithBLOBs(StockBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar
     *
     * @mbggenerated
     */
    List<StockBar> selectByExample(StockBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockBar record, @Param("example") StockBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") StockBar record, @Param("example") StockBarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_bar
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockBar record, @Param("example") StockBarExample example);
}